version: "2"

run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - asasalint
    - bodyclose
    - nosprintfhostport
    - durationcheck
    - errname
    - goconst
    - gocyclo
    - interfacebloat
    - makezero
    - nilerr
    - gosec
    - govet
    - ineffassign
    - nakedret
    - copyloopvar
    - staticcheck
    - unused
    - asciicheck

  exclusions:
    paths:
      - vendor
      - tools
      - 3rdmocks
      - third_party
      - tmp
      - mocks

  settings:
    nakedret:
      max-func-lines: 59
    gosec:
      excludes:
        - G115
        - G301
        - G304
        - G101
        - G104
    asasalint:
      exclude:
        - Append
        - \.Wrapf
      use-builtin-exclusions: false

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      simplify: false
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'
