run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly

issues:
  exclude-dirs:
    - vendor
    - tools
    - 3rdmocks
    - thirdpart
    - tmp
    - mocks
    
linters-settings:
  nakedret:
    max-func-lines: 59
  misspell:
    locale: US
    ignore-words:
      - hicloud
  gofmt:
    simplify: false
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'
  prealloc:
    simple: false
    range-loops: true
    for-loops: true
  errcheck:
    check-type-assertions: false
  gocritic:
    disabled-checks:
      - captLocal
  nilnil:
    checked-types:
      - ptr
      - func
      - iface
      - map
      - chan
  asasalint:
    exclude:
      - Append
      - \.Wrapf
    use-builtin-exclusions: false
    ignore-test: true
  usestdlibvars:
    http-method: true
    http-status-code: true
    time-weekday: true
    time-month: true
    time-layout: true
    crypto-hash: true
    default-rpc-path: true
    sql-isolation-level: true
    tls-signature-scheme: true
    constant-kind: true
  gosec:
    excludes:
      - G115

linters:
  disable-all: true
  enable:
    - usestdlibvars
    - asasalint
    - bodyclose
    # - nolintlint
    - nosprintfhostport
    - prealloc
    - durationcheck
    - errname
    - goconst
    - gocyclo
    - gocognit
    - interfacebloat
    - makezero
    - nilerr
    - nilnil
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - copyloopvar
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - asciicheck
    - nestif
    - errcheck
    - gocritic
