// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	util "github.com/projecteru2/yavirt/util"
	mock "github.com/stretchr/testify/mock"
)

// Locker is an autogenerated mock type for the Locker type
type Locker struct {
	mock.Mock
}

// Lock provides a mock function with given fields: _a0
func (_m *Locker) Lock(_a0 context.Context) (util.Unlocker, error) {
	ret := _m.Called(_a0)

	var r0 util.Unlocker
	if rf, ok := ret.Get(0).(func(context.Context) util.Unlocker); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(util.Unlocker)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
