// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Qmp is an autogenerated mock type for the Qmp type
type Qmp struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Qmp) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CloseFile provides a mock function with given fields: handle
func (_m *Qmp) CloseFile(handle int) error {
	ret := _m.Called(handle)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(handle)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exec provides a mock function with given fields: cmd, args, stdio
func (_m *Qmp) Exec(cmd string, args []string, stdio bool) ([]byte, error) {
	ret := _m.Called(cmd, args, stdio)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []string, bool) ([]byte, error)); ok {
		return rf(cmd, args, stdio)
	}
	if rf, ok := ret.Get(0).(func(string, []string, bool) []byte); ok {
		r0 = rf(cmd, args, stdio)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, []string, bool) error); ok {
		r1 = rf(cmd, args, stdio)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecStatus provides a mock function with given fields: pid
func (_m *Qmp) ExecStatus(pid int) ([]byte, error) {
	ret := _m.Called(pid)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]byte, error)); ok {
		return rf(pid)
	}
	if rf, ok := ret.Get(0).(func(int) []byte); ok {
		r0 = rf(pid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(pid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FlushFile provides a mock function with given fields: handle
func (_m *Qmp) FlushFile(handle int) error {
	ret := _m.Called(handle)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(handle)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OpenFile provides a mock function with given fields: path, mode
func (_m *Qmp) OpenFile(path string, mode string) ([]byte, error) {
	ret := _m.Called(path, mode)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]byte, error)); ok {
		return rf(path, mode)
	}
	if rf, ok := ret.Get(0).(func(string, string) []byte); ok {
		r0 = rf(path, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(path, mode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadFile provides a mock function with given fields: handle, p
func (_m *Qmp) ReadFile(handle int, p []byte) (int, bool, error) {
	ret := _m.Called(handle, p)

	var r0 int
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(int, []byte) (int, bool, error)); ok {
		return rf(handle, p)
	}
	if rf, ok := ret.Get(0).(func(int, []byte) int); ok {
		r0 = rf(handle, p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int, []byte) bool); ok {
		r1 = rf(handle, p)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(int, []byte) error); ok {
		r2 = rf(handle, p)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SeekFile provides a mock function with given fields: handle, offset, whence
func (_m *Qmp) SeekFile(handle int, offset int, whence int) (int, bool, error) {
	ret := _m.Called(handle, offset, whence)

	var r0 int
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, int) (int, bool, error)); ok {
		return rf(handle, offset, whence)
	}
	if rf, ok := ret.Get(0).(func(int, int, int) int); ok {
		r0 = rf(handle, offset, whence)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int, int, int) bool); ok {
		r1 = rf(handle, offset, whence)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(int, int, int) error); ok {
		r2 = rf(handle, offset, whence)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// WriteFile provides a mock function with given fields: handle, buf
func (_m *Qmp) WriteFile(handle int, buf []byte) error {
	ret := _m.Called(handle, buf)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []byte) error); ok {
		r0 = rf(handle, buf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewQmp interface {
	mock.TestingT
	Cleanup(func())
}

// NewQmp creates a new instance of Qmp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewQmp(t mockConstructorTestingTNewQmp) *Qmp {
	mock := &Qmp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
