env = "dev"
prof_http_port = 9999
bind_http_addr = "0.0.0.0:9696"
bind_grpc_addr = "0.0.0.0:9697"
graceful_timeout = "20s"
virt_timeout = "1h"
health_check_timeout = "2s"
qmp_connect_timeout = "8s"
cni_plugin_path = "/usr/bin/yavirt-cni"
cni_config_path = "/etc/cni/net.d/yavirt-cni.conf"

resize_volume_min_ratio = 0.05
resize_volume_min_size = 10737418240

min_cpu = 1
max_cpu = 64
min_memory = 1073741824
max_memory = 68719476736
min_volume = 1073741824
max_volume = 1099511627776
max_volumes_count = 8
max_snapshots_count = 30
snapshot_restorable_days = 7

meta_timeout = "1m"
meta_type = "etcd"

virt_dir = "/tmp/virt"
virt_bridge = "virbr0"
virt_cpu_cache_passthrough = true

calico_gateway = "yavirt-cali-gw"
calico_pools = ["clouddev"]
calico_etcd_env = "ETCD_ENDPOINTS"

log_level = "info"

etcd_prefix = "/yavirt-dev/v1"
etcd_endpoints = ["http://127.0.0.1:2379"]

ga_disk_timeout = "16m"
ga_boot_timeout = "30m"

recovery_on = false
recovery_max_retries = 2
recovery_retry_interval = "3m"
recovery_interval = "10m"

[host]
name = "host1"
subnet = "127.0.0.1"
cpu = 4
memory = "1g"
storage = "40g"
network = "calico"

[core]
addrs = ["127.0.0.1:5001"]
username = "admin"
password = "password"
status_check_interval = "64s"
nodestatus_ttl = "16m"
