name: test

on:
  push:
    tags:
      - '!v*'
    branches:
      - '*'
  pull_request:

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup go"
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libvirt-dev make genisoimage libguestfs-dev libcephfs-dev librbd-dev librados-dev
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libvirt-dev make genisoimage libguestfs-dev libcephfs-dev librbd-dev librados-dev

      - name: unit tests
        run: make test
